// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQz8hMQ3WtODKX3pkcckpcZDXCtGRITPI',
    appId: '1:1025273190836:web:1ad5d3b24355c8950a3ae1',
    messagingSenderId: '1025273190836',
    projectId: 'constro-77f9b',
    authDomain: 'constro-77f9b.firebaseapp.com',
    storageBucket: 'constro-77f9b.appspot.com',
    measurementId: 'G-PXSKV4G0VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OZYKm0ycXKWKJX9ZCf4XQVssl1Kqi0Y',
    appId: '1:1025273190836:android:04a1f422dcd2f8bd0a3ae1',
    messagingSenderId: '1025273190836',
    projectId: 'constro-77f9b',
    storageBucket: 'constro-77f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAF7_a0fzqCCDCbdjBOK-7p5T1woburQ',
    appId: '1:1025273190836:ios:bda2bbb6a4b4398c0a3ae1',
    messagingSenderId: '1025273190836',
    projectId: 'constro-77f9b',
    storageBucket: 'constro-77f9b.appspot.com',
    iosBundleId: 'com.example.constro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAF7_a0fzqCCDCbdjBOK-7p5T1woburQ',
    appId: '1:1025273190836:ios:d6990c62db84280a0a3ae1',
    messagingSenderId: '1025273190836',
    projectId: 'constro-77f9b',
    storageBucket: 'constro-77f9b.appspot.com',
    iosBundleId: 'com.example.constro.RunnerTests',
  );
}
